unit History;

interface

const
  HistoryID = 100;
  DirHistoryID = 101;
  FindHistoryID = 102;
  ReplaceHistoryID = 103;
  OptionsHistoryID = 104;
  TitleHistoryID = 105;
  PathHistoryID = 106;
  ParamsHistoryID = 107;
  MacroTitleHistoryId = 108;
  MacroInputBoxHistoryId = 109;
  GetAddrHistoryID = 110;
  PromptHistoryID = 111;
  FPromptHistoryID = 112;
  FNameHistoryID = 113;
  FindFileHistoryID = 114;
  WatchHistoryID = 115;
  MaskHistoryID = 116;
  StringHistoryID = 117;
  ValueHistoryID = 118;
  ReopenHistoryID = 119;
  FiltersHistoryID = 120;
  CalcHistoryID = 121;
  DelimsHistoryID = 122;
  AlarmMsgHistoryID = 123;
  DateHistoryID = 124;
  TimeHistoryID = 125;
  LogHistoryID = 126;
  PhoneNameHistoryID = 127;
  PhoneHistoryID = 128;
  PhoneNotesHistoryID = 129;
  TermcapNameHistoryID = 130;
  TermcapIdenHistoryID = 131;
  XLATNameHistoryID = 132;
  PaletteHistoryID = 133;
  HelpNameHistoryID = 134;
  PhoneEntryHistoryID = 135;
  PrnDeviceHistoryID = 136;
  FontFileHistoryID = 137;
  PrnInitHistoryID = 138;
  RedirHistoryID = 139;
  HelpHistoryID = 140;
  FieldNameHistoryID = 141;
  AdvancedFilterHistoryID = 142;
  FilterNameHistoryID = 143;
  FilterSizeHistoryID = 144;
  GoToLineNumHistoryID = 145;
  GoToHexAddrHistoryID = 146;
  EnvHistoryID = 147;
  ExprHistoryID = 148;
  MacroNameHistoryID = 149;
  ModemSetupHistoryID = 150;
  HexMaskHistoryID = 151;
  FindPhoneHistoryID = 152;
  NetListHistoryID = 153;
  DecoderTitleHistoryID = 154;
  SearchDirHistoryID = 190;
  SyntaxHistoryID = 191;
  RegExpDlgHistoryID = 192;
  FilterSourceHistoryID = 193;
  VolumeLabelHistoryID = 194;
  SerialNumberHistoryID = 195;
{ 199, 200 are reserved for internal use }
  Histories = 60;
  HistoryOpened: Boolean = False;

implementation

end.