
This package is an MsDOS executable release of
mawk 1.0, an interpreter for the AWK programming
language as defined in Aho, Kernighan and Weinberger,
"The AWK Programming Language", Addison-Wesley, 1988.
Mawk is compatible with SystemVR3 nawk.

The complete source code for mawk 1.0 can be obtained
free from comp.sources.reviewed, volume01 or
by anonymous ftp from oxy.edu in ftp/public/mawk1.0.tar.Z.

Mawk is copyrighted 1991 by Michael D. Brennan.
Mawk is distributed without warranty under the terms of the
GNU General Public Licence, version 2, June 1991.
If you redistribute this binary, it is your responsibility to
make sure the recipient is aware that he or she can obtain
the complete source for free, and that he or she is in turn
aware of the copyright and terms of redistribution. (The easy
way to do this is to give them all the below listed files).


The files in this distribution are:

READFIRS.T		this file
README			README file from the complete 
			distribution
COPYING			GNU GPL v2
mawk.doc		Ascii form of unix style man pages
NOTES			added info about DOS mawk

mawk.exe		small model mawk
bmawk.exe		large model mawk( "big mawk" )


These .exe's were compiled with TurboC++1.0.

Some of the NOTES and README are about installation from
source and not relevant unless you are making mawk.


bug reports and correspondence to:

Mike Brennan
brennan@boeing.com

